version: '3'
services:
    database:
        image: mariadb:10.3.14-bionic
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html/
        environment:
            - APACHE_DOCUMENT_ROOT
        depends_on:
            - database
